# Generated by Django 5.0.5 on 2024-11-08 13:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(blank=True, max_length=300)),
                ('seen', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField(blank=True, editable=False, null=True, validators=[django.core.validators.MinValueValidator(1, 'Must be at least 1')])),
                ('transaction_id', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('price_paid', models.FloatField(blank=True, editable=False, null=True, validators=[django.core.validators.MinValueValidator(1, 'Must be at least 1')])),
                ('story_title', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('user', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
