# Generated by Django 5.0.5 on 2024-09-11 23:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='price_paid',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, 'Must be at least 1')]),
        ),
        migrations.AddField(
            model_name='notification',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, 'Must be at least 1')]),
        ),
        migrations.AddField(
            model_name='notification',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
