# Generated by Django 5.0.5 on 2024-09-11 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_notification_price_paid_notification_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='price_paid',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, 'Must be at least 1')]),
        ),
    ]
