# Generated by Django 5.0.5 on 2024-09-11 23:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_notification_price_paid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='story_title',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='price_paid',
            field=models.FloatField(blank=True, editable=False, null=True, validators=[django.core.validators.MinValueValidator(1, 'Must be at least 1')]),
        ),
        migrations.AlterField(
            model_name='notification',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, validators=[django.core.validators.MinValueValidator(1, 'Must be at least 1')]),
        ),
        migrations.AlterField(
            model_name='notification',
            name='transaction_id',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
