# Generated by Django 5.0.5 on 2024-08-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_stories', '0004_alter_story_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_public',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
