# Generated by Django 5.0.5 on 2024-09-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_stories', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
