# Generated by Django 5.0.5 on 2024-09-02 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate_stories', '0007_order_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
