# Generated by Django 5.0.5 on 2024-09-02 21:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_stories', '0008_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='promotional_tokens',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='token',
            name='purchased_tokens',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
