# Generated by Django 5.0.5 on 2024-09-06 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('generate_stories', '0009_alter_token_promotional_tokens_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedEmail',
            fields=[
                ('auditmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.auditmixin')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            bases=('common.auditmixin', models.Model),
        ),
    ]
