# Generated by Django 5.0.5 on 2024-11-08 13:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.CharField(blank=True, default='', max_length=100)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(blank=True, choices=[('Placed', 'Placed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=100)),
                ('transferred', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
